# Generated by Django 5.2.7 on 2025-10-05 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='telemetry.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag', models.CharField(blank=True, max_length=64)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telemetry.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='telemetry.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bp_sys', models.IntegerField(blank=True, null=True)),
                ('bp_dia', models.IntegerField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device', '-ts'], name='telemetry_r_device__1df21a_idx')],
            },
        ),
    ]
