# Generated by Django 5.2.7 on 2025-10-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('bp_sys', models.IntegerField(blank=True, null=True)),
                ('bp_dia', models.IntegerField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('battery_pct', models.FloatField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='telemetry.device')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vitals', to='telemetry.person')),
            ],
            options={
                'indexes': [models.Index(fields=['-updated_at'], name='telemetry_c_updated_f5e4fd_idx'), models.Index(fields=['ts'], name='telemetry_c_ts_1a7e4c_idx')],
            },
        ),
    ]
