# Generated by Django 5.2.7 on 2025-11-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_currentvital_hops_currentvital_path_reading_hops_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvital',
            name='hops',
        ),
        migrations.RemoveField(
            model_name='currentvital',
            name='path',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='hops',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='path',
        ),
    ]
