# Generated by Django 5.2.7 on 2025-11-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_remove_currentvital_hops_remove_currentvital_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentvital',
            name='hops',
            field=models.IntegerField(blank=True, help_text='Last hop count from mesh', null=True),
        ),
        migrations.AddField(
            model_name='currentvital',
            name='path',
            field=models.CharField(blank=True, help_text='Last communication path, e.g. LORA or GSM', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='hops',
            field=models.IntegerField(blank=True, help_text='Hop count used in mesh routing, if applicable', null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='path',
            field=models.CharField(blank=True, help_text='Last communication path, e.g. LORA or GSM', max_length=16, null=True),
        ),
    ]
